apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: product-return-exchange-deployment
  labels:
    app: product-return-exchange
=======
  name: product-deployment
>>>>>>> 324aeb2a1969e0c5053aed1237a1043944599c47
spec:
  replicas: 2
  selector:
    matchLabels:
<<<<<<< HEAD
      app: product-return-exchange
  template:
    metadata:
      labels:
        app: product-return-exchange
    spec:
      containers:
      - name: product-return-exchange-container
        image: santhoshii/product_system:latest
        ports:
        - containerPort: 3007
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
=======
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: santhoshii/njs-app:latest
        ports:
        - containerPort: 3005
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/returnExchangeDB"
        - name: PORT
          value: "3005"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "returnExchangeDB"
 
>>>>>>> 324aeb2a1969e0c5053aed1237a1043944599c47
