apiVersion: v1
kind: Service
metadata:
  name: product-return-exchange-service
spec:
  selector:
    app: product-return-exchange  # Must match the labels of the deployment
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 3007  
  type: LoadBalancer  # Change to ClusterIP or NodePort as needed
