apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: product-return-exchange-service
spec:
  selector:
    app: product-return-exchange  # Must match the labels of the deployment
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 3007  
  type: LoadBalancer  # Change to ClusterIP or NodePort as needed
=======
  name: nodejs-service
spec:
  type: LoadBalancer 
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: app-and-mongodb
>>>>>>> 324aeb2a1969e0c5053aed1237a1043944599c47
